# render.yaml - BEZPIECZNA WERSJA (bez sekretów)
services:
  - type: web
    name: hardbanrecords-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY  
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      # DATABASE_URL i GROQ_API_KEY będą skonfigurowane ręcznie w Render dashboard