"""Create users and releases tables

Revision ID: 42ccc933830f
Revises: 
Create Date: 2025-08-21 02:18:10.836703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ccc933830f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MUSIC_CREATOR', 'BOOK_AUTHOR', 'ELEARNING_INSTRUCTOR', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('audio_file_path', sa.String(), nullable=True),
    sa.Column('release_meta', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_artist'), 'releases', ['artist'], unique=False)
    op.create_index(op.f('ix_releases_id'), 'releases', ['id'], unique=False)
    op.create_index(op.f('ix_releases_title'), 'releases', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_title'), table_name='releases')
    op.drop_index(op.f('ix_releases_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_artist'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
